/* THIS FILE WAS GENERATED BY PAYLOAD. */
/* DO NOT MODIFY IT DIRECTLY. */
import type { ReactNode } from "react";
import type { ServerFunctionClient } from "payload";

import config from "@payload-config";
import { RootLayout, handleServerFunctions } from "@payloadcms/next/layouts";
import "@payloadcms/next/css";
import { importMap } from "./admin/importMap.js";

type Args = {
  children: ReactNode;
};

const Layout = ({ children }: Args) => {
  const serverFunction: ServerFunctionClient = async (args) => {
    "use server";

    return handleServerFunctions({
      ...args,
      config,
      importMap,
    });
  };

  return (
    <RootLayout
      config={config}
      importMap={importMap}
      serverFunction={serverFunction}
    >
      {children}
    </RootLayout>
  );
};

export default Layout;
