/* THIS FILE WAS GENERATED BY PAYLOAD. */
/* DO NOT MODIFY IT DIRECTLY. */
import type { ReactNode } from 'react'

import config from '@payload-config'
import { RootLayout, handleServerFunctions } from '@payloadcms/next/layouts'
import '@payloadcms/next/css'

type Args = {
  children: ReactNode
}

const serverFunction = handleServerFunctions(config)

const Layout = ({ children }: Args) => (
  <RootLayout config={config} serverFunction={serverFunction}>
    {children}
  </RootLayout>
)

export default Layout
