// =============================================================================
// Re-export Payload generated types
// =============================================================================
export type {
  Post,
  Media,
  Category,
  Tag,
  Author,
  Page,
  GridLayout,
  User,
} from "../../payload-types";

// Import for use in helper functions
import type { Post, Media, Author, Category, Tag } from "../../payload-types";

// =============================================================================
// Utility types
// =============================================================================
export type Maybe<T> = T | null | undefined;

// =============================================================================
// Helper functions for working with Payload types
// =============================================================================

// Helper to get featured image URL from either Payload media or legacy WP field
export function getPostImageUrl(post: Post): string | null {
  if (post.featuredImage && typeof post.featuredImage === "object") {
    return (post.featuredImage as Media).url ?? null;
  }
  if (post.wpFeaturedImage?.url) {
    return post.wpFeaturedImage.url;
  }
  return null;
}

export function getPostImageAlt(post: Post): string {
  if (post.featuredImage && typeof post.featuredImage === "object") {
    return (post.featuredImage as Media).alt || "";
  }
  if (post.wpFeaturedImage?.alt) {
    return post.wpFeaturedImage.alt;
  }
  return "";
}

// Helper to get author name from populated or ID reference
export function getAuthorName(post: Post): string | null {
  if (post.author && typeof post.author === "object") {
    return (post.author as Author).name;
  }
  return null;
}

// Helper to get categories as objects (when depth is used)
export function getPopulatedCategories(post: Post): Category[] {
  if (!post.categories) return [];
  return post.categories.filter(
    (c): c is Category => typeof c === "object" && c !== null
  );
}

// Helper to get tags as objects (when depth is used)
export function getPopulatedTags(post: Post): Tag[] {
  if (!post.tags) return [];
  return post.tags.filter(
    (t): t is Tag => typeof t === "object" && t !== null
  );
}

// =============================================================================
// Legacy type aliases for backwards compatibility during migration
// These can be removed once all code uses the generated types directly
// =============================================================================
export type PayloadPost = Post;
export type PayloadMedia = Media;
export type PayloadAuthor = Author;
export type PayloadCategory = Category;
export type PayloadTag = Tag;

// =============================================================================
// Grid/Block Types (not generated by Payload - custom app types)
// =============================================================================

// Position types
export interface GridPosition {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const objectPositions = [
  "top",
  "bottom",
  "center",
  "left",
  "right",
] as const;

export type ObjectPosition = (typeof objectPositions)[number];

// Common fields for all blocks
interface BaseBlock {
  uId: string;
  gridPosition: GridPosition;
  mobilePriority: number | null;
}

// Custom fields for story blocks (allow null to match Payload's generated types)
export interface CustomPostFields {
  antetitulo?: string | null;
  chamadaDestaque?: string | null;
  chamadaManchete?: string | null;
}

// Specific block types
export interface StoryBlock extends BaseBlock, CustomPostFields {
  blockType: "story";
  databaseId: number;
  postId: string;
  title?: string;
  style: "classic" | "modern";
  orientation: "horizontal" | "vertical";
  objectPosition: ObjectPosition;
  hideImage: boolean;
  reverse: boolean;
  expandImage: boolean;
  extraBigTitle: boolean;
  // Controls the background color used for postFields.antetitulo in Classic layout
  // 'auto' uses category detection (opiniao -> blue, otherwise noticia -> primary)
  antetituloColor?: "auto" | "noticia" | "opiniao";
}

export interface CategoryBlock extends BaseBlock {
  blockType: "category";
  categoryId?: string; // Payload category ID (preferred)
  wpCategoryId?: number; // WordPress database ID (legacy/fallback)
  wpCategoryName: string;
  postsPerPage: number;
}

export interface StaticBlock extends BaseBlock {
  blockType: "static";
  title: string;
  content: string;
  type: StaticBlockType;
}

// Canonical list of static block type strings (runtime + type-level source of truth)
export const STATIC_BLOCK_TYPES = [
  "newsletter",
  "podcast",
  "divider",
  "donation",
  "accountsCounter",
  "bookPresale",
] as const;

export type StaticBlockType = (typeof STATIC_BLOCK_TYPES)[number];

// Union type for all blocks
export type Block = StoryBlock | CategoryBlock | StaticBlock;

// Grid state
export interface GridState {
  blocks: Block[];
  createdAt: string;
}

// Fields that can be overridden
export type OverridableField = "title" | keyof CustomPostFields;

// Block type discriminator
export type BlockType = Block["blockType"];

// Helper type to extract fields that can be modified in settings
export type BlockSettings<T extends Block> = T extends StoryBlock
  ? Pick<
      StoryBlock,
      | "mobilePriority"
      | "style"
      | "orientation"
      | "objectPosition"
      | "reverse"
      | "hideImage"
      | "expandImage"
      | "extraBigTitle"
      | "antetituloColor"
    >
  : T extends CategoryBlock
    ? Pick<CategoryBlock, "mobilePriority" | "postsPerPage">
    : T extends StaticBlock
      ? Pick<StaticBlock, "mobilePriority">
      : never;
