/* THIS FILE WAS GENERATED BY PAYLOAD. */
/* DO NOT MODIFY IT DIRECTLY. */
import config from '@payload-config'
import { GRAPHQL_GET, GRAPHQL_POST } from '@payloadcms/next/routes'

export const GET = GRAPHQL_GET(config)
export const POST = GRAPHQL_POST(config)
